#!/bin/bash
# -*- bash -*-

: << =cut

=head1 NAME

go_echarger_current - Plugin to monitor energy currents

=head1 CONFIGURATION

You just need to set the host like this:

 [go_echarger_*]
 env.host go-echarger.home.well-adjusted.de

=head1 AUTHORS

=over

=item 2021.04.30 Initial version by Jochen Spieker <js@wim.re>

=back

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=contrib
 #%# capabilities=autoconf

=cut

#set -x
#set -u

host=${host:-go-echarger}
status=""

get_status() {
	echo "${status}"
}

current_format() {
	if [ -n "$1" ]; then
		printf "%.1f" $(echo "$1 / 10" | bc -l)
	else
		echo "U"
	fi
}

limit_format() {
	if [ -n "$1" ]; then
		printf "%.1f" "$1"
	else
		echo "U"
	fi
}

get_cable_current() {
	limit_format $(get_status | jq ".cbl | tonumber")
}

get_line_current() {
	# $1 must be 1, 2, 3
	local line=$1
	if [ "${line}" -lt 1 ] || [ "${line}" -gt 3 ]; then
		exit
	fi
	local idx=$(echo "$line + 3" | bc)
	current_format $(get_status | jq ".nrg[${idx}]")
}

get_current_level() {
	limit_format $(get_status | jq ".amp | tonumber")
}

get_max_configured_current() {
	limit_format $(get_status | jq ".ama | tonumber")
}

get_adapter_status() {
	local adi=$(get_status | jq ".adi | tonumber")
	if [ -n "$adi" ]; then
		echo "$adi"
	else
		echo "U"
	fi
}

case $1 in
	config)
        cat <<EOF
graph_title go-eCharger Currents
graph_args --lower-limit 0
graph_vlabel Ampere
graph_info go-eCharger Currents
graph_category go_eCharger
graph_printf %0.1lf
graph_data_size custom 7d, 30m for 30d, 2h for 365d, 1d for 3650d
EOF

		echo "line1.label Line 1"
		echo "line2.label Line 2"
		echo "line3.label Line 3"
		echo "adapter.label Adapter Limit"
		echo "cable.label Cable Limit"
		echo "level.label Selected Level"
		echo "maximum.label Absolute Maximum"

        exit 0
		;;
	autoconf)
		if ! jq --version > /dev/null; then
			echo "no ('jq' not found. Is it installed and in PATH?)"
		elif ! echo "" | nc -q1 "$host" "80" > /dev/null 2>&1 ; then
			echo "no (Connection to ${host}:80 failed.)"
		else
			echo "yes"
		fi
		exit 0
		;;
esac 

if [ -z "${status}" ]; then
	status=$(curl -s http://${host}/mqtt)
fi

echo "line1.value $(get_line_current 1)"
echo "line2.value $(get_line_current 2)"
echo "line3.value $(get_line_current 3)"

if [ "$(get_adapter_status)" -gt 1 ]; then
	echo "adapter.value 16"
else
	echo "adapter.value 0"
fi

echo "cable.value $(get_cable_current)"
echo "level.value $(get_current_level)"
echo "maximum.value $(get_max_configured_current)"

exit 0
